-- 상반기 아이스크림 총주문량이 3,000보다 높으면서 아이스크림의 주 성분이 과일인 아이스크림의 맛을 총주문량이 큰 순서대로 조회하는 SQL 문을 작성해주세요.


-- where문만
SELECT f.flavor
FROM FIRST_HALF f, ICECREAM_INFO i
WHERE f.FLAVOR = i.FLAVOR AND f.TOTAL_ORDER >= 3000 AND i.INGREDIENT_TYPE = 'fruit_based'
ORDER BY f.TOTAL_ORDER DESC

-- join, Using, 정규식 사용
SELECT FLAVOR
FROM FIRST_HALF A JOIN ICECREAM_INFO B
USING (FLAVOR)
WHERE A.TOTAL_ORDER > 3000 AND B.INGREDIENT_TYPE REGEXP '^fruit'
ORDER BY TOTAL_ORDER DESC

-- LEFT Join, On 사용
SELECT a.FLAVOR
FROM FIRST_HALF a
LEFT JOIN  ICECREAM_INFO b
ON a.FLAVOR = b.FLAVOR
WHERE INGREDIENT_TYPE = "fruit_based" AND TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC